name = "SimplePIETools"
uuid = "35697508-26d7-4c4a-82c6-3a48c17cc2d4"
authors = ["Chen Huang"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
